USE LearnSphereDB;

CREATE TABLE Account (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	Username NVARCHAR(50) UNIQUE NOT NULL,
	Email NVARCHAR(50) UNIQUE NOT NULL,
	PasswordHash NVARCHAR(255) NOT NULL
)

CREATE TABLE Administrator (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	AccountID INT NOT NULL,

	CONSTRAINT FK_AccountID_Administrator 
	FOREIGN KEY (AccountID) 
	REFERENCES Account(ID) 
	ON DELETE CASCADE
)

CREATE TABLE Learner (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	AccountID INT NOT NULL,

	CONSTRAINT FK_AccountID_Learner
	FOREIGN KEY (AccountID) REFERENCES Account(ID)
	ON DELETE CASCADE
)

CREATE TABLE Domain (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	DomainName NVARCHAR(50) UNIQUE	
)

CREATE TABLE Educator (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	AccountID INT NOT NULL,
	DomainName NVARCHAR(50) NOT NULL DEFAULT 'General Education',

	CONSTRAINT FK_AccountID_Educator
	FOREIGN KEY (AccountID) REFERENCES Account(ID)
	ON DELETE CASCADE,

	CONSTRAINT FK_DomainName_Educator
	FOREIGN KEY (DomainName) REFERENCES Domain(DomainName) 
	ON DELETE SET DEFAULT
)

CREATE TABLE EducatorApplication (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	Username NVARCHAR(50) NOT NULL,
	Email NVARCHAR(50) NOT NULL,
	PasswordHash NVARCHAR(255) NOT NULL,
	DomainName NVARCHAR(50) NOT NULL DEFAULT 'General Education',
	Completed BIT NOT NULL DEFAULT 0,

	CONSTRAINT FK_DomainName_EducatorApplication
	FOREIGN KEY (DomainName) REFERENCES Domain(DomainName) 
	ON DELETE SET DEFAULT
)

CREATE UNIQUE NONCLUSTERED INDEX UIX_PendingUsername_EducatorApplication
ON EducatorApplication (Username)
WHERE Completed = 0;

CREATE UNIQUE NONCLUSTERED INDEX UIX_PendingEmail_EducatorApplication
ON EducatorApplication (Email)
WHERE Completed = 0;

CREATE TABLE Certification (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	ApplicationID INT NOT NULL,
	
	CONSTRAINT FK_ApplicationID_EducatorApplication
	FOREIGN KEY (ApplicationID) REFERENCES EducatorApplication(ID) 
	ON DELETE CASCADE
)


CREATE TABLE LearningResource (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	Title NVARCHAR(50) UNIQUE NOT NULL,
	Author NVARCHAR(50) NOT NULL,
	PublicationYear INT NOT NULL,
	Category NVARCHAR(50) NOT NULL,
	Locator NVARCHAR(500) NOT NULL,
	DomainID INT NOT NULL,
	SharerID INT NOT NULL,

	CONSTRAINT FK_DomainID_LearningResource 
	FOREIGN KEY (DomainID) REFERENCES Domain(ID)
	ON DELETE CASCADE,

	CONSTRAINT FK_SharerID_LearningResource 
	FOREIGN KEY (SharerID) REFERENCES Account(ID)
	ON DELETE CASCADE,

	CONSTRAINT CHK_PublicationYear CHECK (PublicationYear BETWEEN 1900 AND 2050),
	CONSTRAINT CHK_Category CHECK (Category IN ('Book', 'Article', 'Lecture', 'Other'))
)

CREATE TABLE Forum (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	Topic NVARCHAR(50) NOT NULL,
	DomainID INT NOT NULL,
	CreatorID INT NOT NULL,

	CONSTRAINT FK_DomainID_Forum 
	FOREIGN KEY (DomainID) REFERENCES Domain(ID)
	ON DELETE CASCADE,

	CONSTRAINT FK_CreatorID_Forum
	FOREIGN KEY (CreatorID) REFERENCES Account(ID)
	ON DELETE CASCADE
)

CREATE TABLE Post (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	Content NVARCHAR(500) NOT NULL,
	CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
	ForumID INT NOT NULL,
	AccountID INT NOT NULL,

	CONSTRAINT FK_ForumID_Post 
	FOREIGN KEY (ForumID) REFERENCES Forum(ID)
	ON DELETE CASCADE,

	CONSTRAINT FK_AccountID_Post 
	FOREIGN KEY (AccountID) REFERENCES Account(ID) -- Delete account's posts before account in runtime
)

CREATE TABLE ForumTag (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	TagName NVARCHAR(50) NOT NULL,
	ForumID INT NOT NULL,

	CONSTRAINT FK_ForumID_ForumTag 
	FOREIGN KEY (ForumID) REFERENCES Forum(ID)
	ON DELETE CASCADE
)

CREATE TABLE Paper (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	Title NVARCHAR(50) NOT NULL,
	EducatorID INT NOT NULL,

	CONSTRAINT FK_EducatorID_Paper 
	FOREIGN KEY (EducatorID) REFERENCES Educator(ID)
	ON DELETE CASCADE
)

CREATE TABLE PaperTag (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	TagName NVARCHAR(50) NOT NULL,
	PaperID INT NOT NULL,

	CONSTRAINT FK_PaperID_PaperTag 
	FOREIGN KEY (PaperID) REFERENCES Paper(ID)
	ON DELETE CASCADE
)

CREATE TABLE Attempt (
	AttemptID INT IDENTITY(1, 1) PRIMARY KEY,
	PaperID INT NOT NULL,
	LearnerID INT NOT NULL,
	Marks INT NOT NULL DEFAULT -1,

	CONSTRAINT Unique_PaperID_LearnerID UNIQUE (PaperID, LearnerID),

	CONSTRAINT FK_PaperID_Attempt
	FOREIGN KEY (PaperID) REFERENCES Paper(ID)
	ON DELETE CASCADE,

	CONSTRAINT FK_LearnerID_Attempt 
	FOREIGN KEY (LearnerID) REFERENCES Learner(ID), -- Delete learner's attempts before learner in runtime

	CONSTRAINT CHK_Marks CHECK (Marks BETWEEN -1 AND 100)
)