USE LearnSphereDB;

CREATE TABLE Administrator (
	AdministratorID INT IDENTITY(1, 1) PRIMARY KEY,
	Username NVARCHAR(50) UNIQUE NOT NULL,
	Email NVARCHAR(50) UNIQUE NOT NULL,
	Password NVARCHAR(50) NOT NULL
)

CREATE TABLE Learner (
	LearnerID INT IDENTITY(1, 1) PRIMARY KEY,
	Username NVARCHAR(50) UNIQUE NOT NULL,
	Email NVARCHAR(50) UNIQUE NOT NULL,
	Password NVARCHAR(50) NOT NULL
)

CREATE TABLE Educator (
	EducatorID INT IDENTITY(1, 1) PRIMARY KEY,
	Username NVARCHAR(50) UNIQUE NOT NULL,
	Email NVARCHAR(50) UNIQUE NOT NULL,
	Password NVARCHAR(50) NOT NULL,
)

CREATE TABLE Domain (
	DomainName NVARCHAR(50) PRIMARY KEY,
	Description NVARCHAR(50) NOT NULL
)

CREATE TABLE LearningResource (
	LearningResourceID INT IDENTITY(1, 1) PRIMARY KEY,
	Title NVARCHAR(50) UNIQUE NOT NULL,
	Author NVARCHAR(50) NOT NULL,
	PublicationYear INT NOT NULL,
	DomainName NVARCHAR(50) NOT NULL,
	Category NVARCHAR(50) NOT NULL,
	Locator NVARCHAR(500) NOT NULL,

	CONSTRAINT FK_DomainName_LearningResource FOREIGN KEY (DomainName) REFERENCES Domain(DomainName),
	CONSTRAINT CHK_PublicationYear CHECK (PublicationYear IS NULL OR PublicationYear BETWEEN 1900 AND 2050),
	CONSTRAINT CHK_Category CHECK (Category IN ('Book', 'Article', 'Lecture', 'Other'))
)

CREATE TABLE Forum (
	ForumID INT IDENTITY(1, 1) PRIMARY KEY,
	Topic NVARCHAR(50) NOT NULL,
	DomainName NVARCHAR(50) NOT NULL,
	Tag1 NVARCHAR(50),
	Tag2 NVARCHAR(50),

	CONSTRAINT FK_DomainName_Forum FOREIGN KEY (DomainName) REFERENCES Domain(DomainName)
)

CREATE TABLE LearnerPost (
	LearnerPostID INT IDENTITY(1, 1) PRIMARY KEY,
	ForumID INT NOT NULL,
	LearnerID INT NOT NULL,
	Content NVARCHAR(500) NOT NULL,
	CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),

	CONSTRAINT FK_ForumID_LearnerPost FOREIGN KEY (ForumID) REFERENCES Forum(ForumID),
	CONSTRAINT FK_LearnerID_LearnerPost FOREIGN KEY (LearnerID) REFERENCES Learner(LearnerID)
)

CREATE TABLE EducatorPost (
	EducatorPostID INT IDENTITY(1, 1) PRIMARY KEY,
	ForumID INT NOT NULL,
	EducatorID INT NOT NULL,
	Content NVARCHAR(500) NOT NULL,
	CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),

	CONSTRAINT FK_ForumID_EducatorPost FOREIGN KEY (ForumID) REFERENCES Forum(ForumID),
	CONSTRAINT FK_EducatorID_EducatorPost FOREIGN KEY (EducatorID) REFERENCES Educator(EducatorID)
)

CREATE TABLE ExamPaper (
	ExamPaperID INT IDENTITY(1, 1) PRIMARY KEY,
	Title NVARCHAR(50) NOT NULL,
	EducatorID INT NOT NULL,
	DomainName NVARCHAR(50) NOT NULL,
	Tag1 NVARCHAR(50),
	Tag2 NVARCHAR(50),

	CONSTRAINT FK_EducatorID_ExamPaper FOREIGN KEY (EducatorID) REFERENCES Educator(EducatorID),
	CONSTRAINT FK_DomainName_ExamPaper FOREIGN KEY (DomainName) REFERENCES Domain(DomainName)
)

CREATE TABLE Assessment (
		ExamPaperID INT NOT NULL,
		LearnerID INT NOT NULL,
		Marks INT,

		CONSTRAINT PK_Assessment PRIMARY KEY (ExamPaperID, LearnerID),
		CONSTRAINT FK_ExamPaperID_Assessment FOREIGN KEY (ExamPaperID) REFERENCES ExamPaper(ExamPaperID),
		CONSTRAINT FK_LearnerID_Assessment FOREIGN KEY (LearnerID) REFERENCES Learner(LearnerID),
		CONSTRAINT CHK_Marks CHECK (Marks IS NULL OR Marks BETWEEN 0 AND 100)
)